name: keepalived
adopt-info: keepalived
summary: High availability VRRP and load-balancing for Linux
description: |
  Keepalived provides simple and robust loadbalancing and high-availability
  to Linux based infrastructures using VRRP and the well-known Linux Virtual
  Server (IPVS) kernel module.

grade: stable
confinement: strict

apps:
  daemon:
    daemon: forking
    command: sbin/keepalived
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
      - kernel-module-control
  keepalived:
    command: sbin/keepalived
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
      - kernel-module-control
  genhash:
    command: bin/genhash
    plugs:
      - network

parts:
  keepalived:
    plugin: autotools
    source: .
    source-type: git
    configflags:
      - --enable-bfd
      - --enable-dbus
      - --enable-json
      - --enable-regex
      - --enable-snmp
      - --enable-snmp-rfc
      - --disable-libipset-dynamic
      - --with-default-config-file=/var/snap/keepalived/current/keepalived.conf
    override-build: |
      snapcraftctl build
      VER=$(grep GIT_COMMIT lib/git-commit.h | cut -d'"' -f2)
      snapcraftctl set-version $VER
    build-packages:
      - iptables-dev
      - libipset-dev
      - libjson-c-dev
      - libglib2.0-dev
      - libmagic-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnfnetlink-dev
      - libpcre2-dev
      - libsnmp-dev
      - libssl-dev
    stage-packages:
      - libnfnetlink0
      - libipset3
      - libjson-c2
      - libglib2.0-0
      - libmagic1
      - libnl-3-200
      - libnl-genl-3-200
      - libpcre2-8-0
      - libsnmp30
